In [18]:
import csv
a = []

print("The given dataset is\n")
with open('Candidate.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        a.append(row)
        print(row)
        
n = len(a[0]) - 1

print("\n\nThe initial hypoethesis is:")
S = ['0'] * n
G =['?'] * n
print("The most specific hypoethesis S0:[0,0,0,0,0,0]")
print("The most specific hypoethesis G0:[?,?,?,?,?,?]\n\n")

print("Candidate Elimination Algorithm Hypothesis version space Computation")
temp = []
for i in range(0,n):
    S[i] = a[0][i]

for i in range(0, len(a)):
    if a[i][n] == 'Yes':
        for j in range(0, n):
            if a[i][j] != S[j]:
                S[j] = '?'
                
        for j in range(0, n):
            for k in range(0, len(temp)):
                if temp[k][j] != S[j] and temp[k][j] != '?':
                    del temp[k]
                    
        print("For training example No: {0} The hypothesis is S{0}".format(i+1),S)
        
        if len(temp) == 0:
            print("For training example No: {0} The hypothesis is G{0}".format(i+1),G)
        else:
            print("For training example No: {0} The hypothesis is G{0}".format(i+1),temp)
            
    if a[i][n] == 'No':
        for j in range(0, n):
            if S[j] != '?' and S[j] != a[i][j]:
                G[j] = S[j]
                temp.append(G)
                G = ['?'] * n
        print("For training example No: {0} The hypothesis is S{0}".format(i+1),S)
        print("For training example No: {0} The hypothesis is S{0}".format(i+1),temp)

The given dataset is

['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes']
['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes']
['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No']
['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']


The initial hypoethesis is:
The most specific hypoethesis S0:[0,0,0,0,0,0]
The most specific hypoethesis G0:[?,?,?,?,?,?]


Candidate Elimination Algorithm Hypothesis version space Computation
For training example No: 1 The hypothesis is S1 ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
For training example No: 1 The hypothesis is G1 ['?', '?', '?', '?', '?', '?']
For training example No: 2 The hypothesis is S2 ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
For training example No: 2 The hypothesis is G2 ['?', '?', '?', '?', '?', '?']
For training example No: 3 The hypothesis is S3 ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
For training example No: 3 The hypothesis is S3 [['Sunny', '?', '?', '?', '?', '?'], ['?

In [21]:
import csv
a = []
print("The given dataset is:")
with open("Candidate.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        a.append(row)
        print(row)
n = len(a[0]) - 1       


print("\n\n\nThe initial hypoethesis is:")
s = ['0'] * n
g = ['?'] * n
print("The most specific hypoethesis S0:[0,0,0,0,0,0]")
print("The most specific hypoethesis G0:[?,?,?,?,?,?]\n\n\n")



for i in range(0, n):
    s[i] = a[0][i]
print("Candidate elimination algorithm Hypoethesis Version Space Computation:")
temp = []    

for i in range(0, len(a)):
    if a[i][n] == 'Yes':
        for j in range(0, n):
            if a[i][j] != s[j]:
                s[j] = '?'
        
        for j in range(0,n):
            for k in range(0, len(temp)):
                if temp[k][j] != '?' and temp[k][j] != s[j]:
                    del temp[k]
                    
        print("For training example No:{0} the hypothesis is S{0}".format(i+1),s)
        
        if len(temp) == 0:
            print("For training example No:{0} the hypothesis is G{0}".format(i+1),g)
        else:
            print("For training example No:{0} the hypothesis is G{0}".format(i+1),temp)
            
    if a[i][n] == 'No':
        for j in range(0, n):
            if s[j] != '?' and s[j] != a[i][j]:
                g[j] = s[j]
                temp.append(g)
                g = ['?'] * n
        print("For training example No:{0} the hypothesis is S{0}".format(i+1),s)
        print("For training example No:{0} the hypothesis is G{0}".format(i+1),temp)

The given dataset is:
['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes']
['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes']
['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No']
['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']



The initial hypoethesis is:
The most specific hypoethesis S0:[0,0,0,0,0,0]
The most specific hypoethesis G0:[?,?,?,?,?,?]



Candidate elimination algorithm Hypoethesis Version Space Computation:
For training example No:1 the hypothesis is S1 ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
For training example No:1 the hypothesis is G1 ['?', '?', '?', '?', '?', '?']
For training example No:2 the hypothesis is S2 ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
For training example No:2 the hypothesis is G2 ['?', '?', '?', '?', '?', '?']
For training example No:3 the hypothesis is S3 ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
For training example No:3 the hypothesis is G3 [['Sunny', '?', '?', '?', '?', '?'], ['?',

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_labels, test_size = 0.30)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
print("The Confusion matrix is")
print(confusion_matrix(y_test, y_pred))
print("Accuracy Matrix")
print(classification_report(y_test, y_pred))
print("The final accuracy score is",metrics.accuracy_score(y_test, classifier.predict(x_test)))

In [1]:
def aStarAlgo(start, stop):
    o = set(start)
    c = set()
    p = {}
    g = {}
    g[start] = 0
    p[start] = start
    
    while len(o) > 0:
        n = None
        for v in o:
            if n == None or g[v] + heu(v) < g[n] + heu(n):
                n = v
        if n == stop or Graph[n] == None:
            pass
        else:
            for (m, w) in get_n(n):
                if m not in o and m not in c:
                    o.add(m)
                    p[m] = n
                    g[m] = g[n] + w
                    
                else:
                    if g[m] > g[n] + w:
                        g[m] = g[n] + w
                        p[m] = n
                        if m in c:
                            c.remove(m)
                            o.add(m)
                            
        if n == None:
            print("Path does not exist")
            return None
        
        if n == stop:
            path = []
            while p[n] != n:
                path.append(n)
                n = p[n]
            path.append(start)
            path.reverse()
            print("Path : {}".format(path))
            return path
        o.remove(n)
        c.add(n)
    print("Path does not exist")
    return None

def get_n(v):
    if v in Graph:
        return Graph[v]
    else:
        return None
        
def heu(n):
    h_dist = {
        'A':10,
        'B':8,
        'C':5,
        'D':7,
        'E':5,
        'F':9,
        'G':2,
        'H':1,
        'I':3,
        'J':0
    }
    return h_dist[n]

Graph = {
    'A':[('B',6),('C',3)],
    'B':[('C',4),('D',1)],
    'C':[('D',2),('E',2)],
    'D':[('C',2),('E',3)],
    'E':[('F',4),('G',1)],
    'F':[('G',3),('H',1)],
    'G':[('H',2)],
    'H':[('I',3)],
    'I':[('E',4),('J',4)]
}

aStarAlgo('A','J')

Path : ['A', 'C', 'E', 'G', 'H', 'I', 'J']


['A', 'C', 'E', 'G', 'H', 'I', 'J']

In [4]:
import numpy as np
X = np.array(([1,3],[4,7],[6,10]))
y = np.array(([90],[80],[98]))
y = y/100

def sigmoid(x):
    return 1/(1 + np.exp(-x))
def derivative_sigmoid(x):
    return x * (1 - x)

epoch = 1
lr = 0.1
inputLayerNeurons = 2
hideenlayerNeurons = 3
outputLayer = 1

wh = np.random.uniform(size=(inputLayerNeurons,hideenlayerNeurons))
bias_hidden = np.random.uniform(size=(1,hideenlayerNeurons))
weight_hidden = np.random.uniform(size=(hideenlayerNeurons,outputLayer))
bias_output = np.random.uniform(size=(1,outputLayer))
print(weight_hidden, "W")
print(weight_hidden.T, "WT")

for i in range(epoch):
    hinp1 = np.dot(X, wh)
    hinp = hinp1 + bias_hidden
    hLayerActivation = sigmoid(hinp)
    
    outinp1 = np.dot(hLayerActivation, weight_hidden)
    outinp = outinp1 + bias_output
    output = sigmoid(outinp)
    
    EO = y - output
    outgrad = derivative_sigmoid(output)
    d_output = EO * outgrad
    
    EH = d_output.dot(weight_hidden.T)
    hidgrad = derivative_sigmoid(hLayerActivation)
    d_hiddenLayer = EH * hidgrad
    
    
    weight_hidden += hLayerActivation.T.dot(d_output) * lr
    bias_hidden += np.sum(d_hiddenLayer, axis = 0, keepdims = True) * lr
    
    wh += X.T.dot(d_hiddenLayer)
    bias_output += np.sum(d_output, axis = 0, keepdims = True) * lr
    
print("Input :\n", str(X))
print("Actual output :\n", str(y))
print("Output:\n", output)

[[0.20281643]
 [0.27640592]
 [0.39073988]] W
[[0.20281643 0.27640592 0.39073988]] WT
Input :
 [[ 1  3]
 [ 4  7]
 [ 6 10]]
Actual output :
 [[0.9 ]
 [0.8 ]
 [0.98]]
Output:
 [[0.80778409]
 [0.81252938]
 [0.81260394]]
