In [3]:
import numpy as np
X = np.array(([1,3],[4,7],[6,10])) # Hours Studied, Hours Slept
y = np.array(([90],[80],[98])) # Test Score
y = y/100 # max test score is 100



#Sigmoid Function
def sigmoid(x): #this function maps any value between 0 and 1
    return 1/(1 + np.exp(-x))
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)



#Variable initialization
epoch=1 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons of output layer



wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bias_hidden=np.random.uniform(size=(1,hiddenlayer_neurons)) #bias matrix to the hidden
weight_hidden=np.random.uniform(size=(hiddenlayer_neurons,output_neurons)) #weight matr
bias_output=np.random.uniform(size=(1,output_neurons)) # matrix to the output layer
print(weight_hidden,"W")
print(weight_hidden.T,"WT")



for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp= hinp1 + bias_hidden #bias_hidden GRADIENT DISCENT
    hlayer_activation = sigmoid(hinp)
    outinp1=np.dot(hlayer_activation,weight_hidden)
    outinp= outinp1+ bias_output
    output = sigmoid(outinp)
    print(output,"output")
    
    
    
    EO = y-output
    outgrad = derivatives_sigmoid(output) 
    d_output = EO * outgrad 
    EH = d_output.dot(weight_hidden.T) 
    hiddengrad = derivatives_sigmoid(hlayer_activation)
    d_hiddenlayer = EH * hiddengrad
    weight_hidden += hlayer_activation.T.dot(d_output) *lr
    bias_hidden += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bias_output += np.sum(d_output, axis=0,keepdims=True) *lr

print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

[[0.93761023]
 [0.35162242]
 [0.06668881]] W
[[0.93761023 0.35162242 0.06668881]] WT
[[0.82269934]
 [0.83125734]
 [0.83175996]] output
Input: 
[[ 1  3]
 [ 4  7]
 [ 6 10]]
Actual Output: 
[[0.9 ]
 [0.8 ]
 [0.98]]
Predicted Output: 
 [[0.82269934]
 [0.83125734]
 [0.83175996]]
